# Copyright 2021, Verizon Media
# Licensed under the terms of the Apache License 2.0. Please see LICENSE file in project root for terms.
version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
