project_name: crypki

gomod:
  proxy: true

env:
  - GO111MODULE=on
  - COSIGN_YES=true
  - CGO_ENABLED=1 # required for miekg/pkcs11


sboms:
- artifacts: binary

builds:
- main: ./cmd/crypki
  goos:
    - linux
  goarch:
    - amd64

dockers:
  - image_templates:
      - "ghcr.io/theparanoids/{{ .ProjectName }}:latest"
      - "ghcr.io/theparanoids/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/theparanoids/{{ .ProjectName }}:{{ .ShortCommit }}"
    dockerfile: Dockerfile

signs:
- cmd: cosign
  signature: "${artifact}.sig"
  certificate: "${artifact}.pem"
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
  artifacts: all
  output: true

docker_signs:
- cmd: cosign
  args:
  - 'sign'
  - '${artifact}'
  artifacts: all
  output: true

release:
  footer: |
    ### Thanks for all contributors!
