name: create release and upload binary

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: get version
      id: v
      run: echo ::set-output name=tag::$( awk -F '/' '{print $NF}' <<< "${GITHUB_REF}" )

    - name: build
      run: |
       go build ./cmd/crypki
       tar -czvf crypki-${{ steps.v.outputs.tag }}-linux.tar.gz --transform 's,^,crypki-${{ steps.v.outputs.tag }}-${OS}/,' crypki

    - name: create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.v.outputs.tag }}
        release_name: ${{ steps.v.outputs.tag }}
        draft: false
        prerelease: false

    - name: upload linux binary
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: crypki-${{ steps.v.outputs.tag }}-linux.tar.gz
        asset_name: crypki-${{ steps.v.outputs.tag }}-linux.tar.gz
        asset_content_type: application/gzip
